function init(self)
	-- Add initialization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	if message_id == hash("interact") then
		if message.right.hash == hash("axe") or message.left.hash == hash("axe") then
			go.delete()
		else
			msg.post("/hud#hud", "show_text", {type = hash("dialog"), content = "You need something here to go further" })
		end
	elseif message_id == hash("trigger_response") then
		msg.post("/hud#hud", "hide_text")
	end
end