-- screen_root.script
-- Dieses Script sitzt auf dem GO namens "root" in jeder Screen-Collection.
-- Aktuell braucht es keinen eigenen Code – die Position wird vom
-- world_manager direkt per go.animate gesetzt.
-- Hier kannst du später Screen-spezifische Init-Logik unterbringen.

go.property("Area", hash(""))
local name = require "world.areas"

function init(self)
	sound.play("root#overworld")
	sound.play("root#waves")
end




function final(self)
	sound.stop("root#waves")
end