function init(self)
	self.left = gui.get_node("l.icon")
	self.right = gui.get_node("r.icon")
	self.textbox = gui.get_node("textbox")
	self.text = gui.get_node("text")

	gui.set_visible(self.textbox, false)
	gui.set_visible(self.text, false)
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	if message_id == hash("show_hands") then
		
		if message.right then
			gui.play_flipbook(self.right, message.right.sprite)
			print(message.right.sprite)
		else
			gui.play_flipbook(self.right, "none")
		end
		
		if message.left then
			gui.play_flipbook(self.left, message.left.sprite)
			print(message.left.sprite)
		else
			gui.play_flipbook(self.left, "none")
		end

	elseif message_id == hash("show_text") then
		gui.set_text(self.text, message.content)
		gui.set_visible(self.textbox, true)
		gui.set_visible(self.text, true)

	elseif message_id == hash("hide_text") then
		gui.set_visible(self.text, false)
		gui.set_visible(self.textbox, false)
	end
end

function on_input(self, action_id, action)
	-- Add input-handling code here. The game object this script is attached to
	-- must have acquired input focus:
	--
	--    msg.post(".", "acquire_input_focus")
	--
	-- All mapped input bindings will be received. Mouse and touch input will
	-- be received regardless of where on the screen it happened.
	-- Learn more: https://defold.com/manuals/input/
	-- Remove this function if not needed
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
