local item_db = require "things.items.item"

go.property("item_id", hash(""))



function init(self)

	local data = item_db.items[self.item_id]

	if not data then
		print("Item nicht gefunden:", self.item_id)
		return
	end
	self.data = data 
	
	-- Sprite setzen
	sprite.play_flipbook("#sprite", self.data.sprite)
	print("Item-URL: " .. msg.url())
end


function on_message(self, message_id, message, sender)
	
	if message_id == hash("interact") then
		if message.right.hash == nil or message.left.hash == nil then
			msg.post(sender, "collect", { object = self.data} )
			msg.post("/hud#hud", "hide_text")
			go.delete()
		else
			print("Hands full")
		end
		
	elseif message_id == hash("trigger_response") then
		if message.enter == true then
			msg.post("/hud#hud", "show_text", { content = self.data.name})
		else
			msg.post("/hud#hud", "hide_text")
		end
	end
end

function on_input(self, action_id, action)
	-- Add input-handling code here. The game object this script is attached to
	-- must have acquired input focus:
	--
	--    msg.post(".", "acquire_input_focus")
	--
	-- All mapped input bindings will be received. Mouse and touch input will
	-- be received regardless of where on the screen it happened.
	-- Learn more: https://defold.com/manuals/input/
	-- Remove this function if not needed
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
