local crafting = require("objects.crafting")
local item_data = require("objects.items")

-- Strecke, die der Spieler beim Betreten eines neuen Bildschirms zurücklegt
local enters = { 
	[hash("center")] = vmath.vector3(0, 0, 0),
	[hash("up")] = vmath.vector3(0, 8, 0),
	[hash("down")] = vmath.vector3(0, -8, 0),
	[hash("right")] = vmath.vector3(8, 0, 0),
	[hash("left")] = vmath.vector3(-8, 0, 0)
}

local function try_craft(self)
	local result_id = crafting.craft(self.left_hand, self.right_hand)

	if result_id then
		-- Hände leeren
		self.left_hand  = nil
		self.right_hand = nil

		-- Gecraftetes Item in die rechte Hand
		self.right_hand = item_data[result_id]

		print("Gecraftet: " .. result_id)
	else
		print("Kein Rezept für diese Kombination.")
	end
end


function init(self)
	msg.post(".", "acquire_input_focus")
	msg.post("#collider", "disable")

	self.current_animation = hash("idle_down")

	sprite.play_flipbook("#sprite", self.current_animation)

	-- Spieler Attribute und Werte
	self.speed = 100
	self.hunger = 100
	self.sleep = 100

	self.dir = vmath.vector3()
	self.correction = vmath.vector3()
	self.pp = vmath.vector3()

	self.object = nil
	self.righthand = nil
	self.lefthand = nil
end


function update(self, dt)
	self.correction = vmath.vector3()
	
	-- normiert den Bewegungsvektor
	if vmath.length(self.dir) > 1 then
		self.dir = vmath.normalize(self.dir)
	end
	--Updated Spieler Position
	local p = go.get_position()
	local new_p = p + self.dir * self.speed * dt
	go.set_position(new_p)

	local animation = self.current_animation

	-- Depending on the direction vector change it to a proper animation:
	if self.dir.x > 0 then
		animation = hash("walk_right")
	elseif self.dir.x < 0 then
		animation = hash("walk_left")
	elseif self.dir.y > 0 then
		animation = hash("walk_up")
	elseif self.dir.y < 0 then
		animation = hash("walk_down")
		
	elseif self.dir.x == 0 and self.dir.y == 0 then
		if self.current_animation == hash("walk_up") then
			animation = hash("idle_up")
		elseif self.current_animation == hash("walk_left") then
			animation = hash("idle_left")
		elseif self.current_animation == hash("walk_right") then
			animation = hash("idle_right")
		elseif self.current_animation == hash("walk_down") then
			animation = hash("idle_down")
		end
	end

	
	-- if the animation we decided to play is different from the xurrent one playing:
	if self.current_animation ~= animation then 
		sprite.play_flipbook("#sprite", animation) -- Play the new Animation
		self.current_animation = animation -- an update the variable tracking the current nimation
	end

	--print("anim: " .. animation)
	print("current: " .. self.current_animation)

	self.dir = vmath.vector3()

	
	-- trigger load at screen edges
	if new_p.y > 480 then
		msg.post("/game#script", "load_screen", { dir = hash("up") })
	elseif new_p.y < 0 then
		msg.post("/game#script", "load_screen", { dir = hash("down") })
	elseif new_p.x > 640 then
		msg.post("/game#script", "load_screen", { dir = hash("right") })
	elseif new_p.x < 0 then
		msg.post("/game#script", "load_screen", { dir = hash("left") })
	end
end


local function activate(self)
	msg.post(".", "acquire_input_focus")					
	msg.post("#collider", "enable")
	
end

function on_message(self, message_id, message, sender)

	if message_id == hash("contact_point_response") then
		-- Get the info needed to move out of collision. We might
		-- get several contact points back and have to calculate
		-- how to move out of all of them by accumulating a
		-- correction vector for this frame:
		if message.distance > 0 then
			-- First, project the accumulated correction onto
			-- the penetration vector
			local proj = vmath.project(self.correction, message.normal * message.distance)
			if proj < 1 then
				-- Only care for projections that does not overshoot.
				local comp = (message.distance - message.distance * proj) * message.normal
				-- Apply compensation
				go.set_position(go.get_position() + comp)
				-- Accumulate correction done
				self.correction = self.correction + comp
			end
		end


	elseif message_id == hash("teleport") then
		print("teleport to: " .. message.dest)
		go.set_position(message.dest)
		
	-- Erkennt, wenn Spieler mit Objekt kollidiert, bzw. Kollision endet
	elseif message_id == hash("trigger_response") then
		if message.enter then
			self.object = message.other_id
		else
			self.object = nil
		end

		-- Spieler sammelt Objekt ein
	elseif message_id == hash("collect") then
		if self.righthand == nil then
			self.righthand = message.object
		elseif self.lefthand == nil then
			self.lefthand = message.object
		end
		msg.post("/hud#hud", "show_hands", {right = self.righthand, left = self.lefthand})
		self.object = nil

		-- Lässt Spieler den neuen Bildschirm betreten
	elseif message_id == hash("enter_screen") then
		-- don't allow player to mess with input while hero walks into screen.
		msg.post(".", "release_input_focus")					
		-- animate in from the edge into next screen, then activate.
		local p = go.get_position()
		local dp = enters[message.dir]
		go.animate(".", "position", go.PLAYBACK_ONCE_FORWARD, p+dp, go.EASING_LINEAR, 0.1, 0, activate)

	end
end


function on_input(self, action_id, action)
		-- Bewegung, Figur läuft per Tastatur in Richtungen
	if action_id == hash("up") then
		self.dir.y = 1
	elseif action_id == hash("down") then
		self.dir.y = -1
	elseif action_id == hash("left") then
		self.dir.x = -1
	elseif action_id == hash("right") then
		self.dir.x = 1
		
		-- Spieler interagiert mit Objekt, je nachdem, was er in den Händen hält
	elseif action_id == hash("interact") and action.pressed and self.object then
			print("interact with ", self.object)
			msg.post(self.object, "interact", { right = self.righthand, left = self.lefthand })

		-- Spieler droppt Item in der linken Hand
	elseif action_id == hash("drop") and action.pressed then
		if self.lefthand then
			print("dropped " .. self.lefthand.hash)
			local props = {item_id = self.lefthand.hash}
			factory.create("#factory", nil, nil, props)
			self.lefthand = nil
			msg.post("/hud#hud", "show_hands", {right = self.righthand, left = self.lefthand})
		end

		-- Spieler wechselt Items der beiden Hände
	elseif action_id == hash("switch") and action.pressed then
		local stored = self.righthand
		self.righthand = self.lefthand
		self.lefthand = stored
		msg.post("/hud#hud", "show_hands", {right = self.righthand, left = self.lefthand})

		-- Spieler vercrafted Items in den Händen, hält Ergebnis in rechter Hand
	elseif action_id == hash("craft") and action.pressed then
		local success, result, err = crafting.craft(self.righthand, self.lefthand)

		if success then
			self.righthand = result
			self.lefthand = nil
		else
			-- err: "missing_items" oder "no_recipe" - für eigenes Feedback im HUD nutzbar
			print("Crafting fehlgeschlagen: " .. err)
		end

		msg.post("/hud#hud", "show_hands", {right = self.righthand, left = self.lefthand})
	end
end